//aws_access_key_id="${AWS_ACCESS_KEY_ID}"
//aws_secret_access_key="${AWS_SECRET_ACCESS_KEY}"
vpc_region="us-west-1"
vpc_name="simon-test-vpc"
vpc_cidr_block="10.0.0.0/16"
availability_zone={"us-west-1": "us-west-1a"}
vpc_public_subnet_1_cidr="10.0.0.0/24"
//vpc_access_from_ip_range="${vpc_access_from_ip_range}"
vpc_private_subnet_1_cidr="10.0.1.0/24"